<?xml version="1.0" encoding="utf-8"?><Database Name="FelBookDB" Class="FelbookDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\FelBookDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FelBookDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Rights" Member="Rights">
    <Type Name="Right">
      <Column Name="InfoID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CanRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanModify" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Right" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Information_Right" Member="Information" ThisKey="InfoID" OtherKey="InfoID" Type="Information" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PassHash" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="User_Right" Member="Rights" ThisKey="UserID" OtherKey="UserID" Type="Right" />
      <Association Name="User_Friendship" Member="Friendships" ThisKey="UserID" OtherKey="UserWhoHas" Type="Friendship" />
      <Association Name="User_Friendship1" Member="Friendships1" ThisKey="UserID" OtherKey="WithWhichUser" Type="Friendship" />
      <Association Name="User_Message" Member="Messages" ThisKey="UserID" OtherKey="FromUser" Type="Message" />
      <Association Name="User_RecieverList" Member="RecieverLists" ThisKey="UserID" OtherKey="UserID" Type="RecieverList" />
      <Association Name="User_MembershipInGroup" Member="MembershipInGroups" Storage="_Memberships" ThisKey="UserID" OtherKey="UserID" Type="MembershipInGroup" />
      <Association Name="User_Information" Member="Informations" ThisKey="UserID" OtherKey="InfoAboutUser" Type="Information" />
    </Type>
  </Table>
  <Table Name="dbo.Friendship" Member="Friendships">
    <Type Name="Friendship">
      <Column Name="UserWhoHas" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WithWhichUser" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeOfFriendship" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="User_Friendship" Member="User" ThisKey="UserWhoHas" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_Friendship1" Member="User1" ThisKey="WithWhichUser" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FromUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Message_RecieverList" Member="RecieverLists" ThisKey="MessageID" OtherKey="MessageID" Type="RecieverList" />
      <Association Name="Message_Information" Member="Informations" ThisKey="MessageID" OtherKey="InfoInMessage" Type="Information" />
      <Association Name="User_Message" Member="User" ThisKey="FromUser" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecieverList" Member="RecieverLists">
    <Type Name="RecieverList">
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Message_RecieverList" Member="Message" ThisKey="MessageID" OtherKey="MessageID" Type="Message" IsForeignKey="true" />
      <Association Name="User_RecieverList" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Membership" Member="MembershipInGroups">
    <Type Name="MembershipInGroup">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeOfMembership" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="User_MembershipInGroup" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Group_MembershipInGroup" Member="Group" ThisKey="GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ParentGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Group_MembershipInGroup" Member="MembershipInGroups" Storage="_Memberships" ThisKey="GroupID" OtherKey="GroupID" Type="MembershipInGroup" />
      <Association Name="Group_Group" Member="Groups" ThisKey="GroupID" OtherKey="ParentGroupID" Type="Group" />
      <Association Name="Group_InfoAboutGroup" Member="InfoAboutGroups" ThisKey="GroupID" OtherKey="GroupID" Type="InfoAboutGroup" />
      <Association Name="Group_Group" Member="Group1" ThisKey="ParentGroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InfoAboutGroup" Member="InfoAboutGroups">
    <Type Name="InfoAboutGroup">
      <Column Name="InfoID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Group_InfoAboutGroup" Member="Group" ThisKey="GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
      <Association Name="Information_InfoAboutGroup" Member="Information" ThisKey="InfoID" OtherKey="InfoID" Type="Information" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Information" Member="Informations">
    <Type Name="Information" Modifier="Abstract">
      <Column Name="InfoID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentInfoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="InfoAboutUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InfoInMessage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeOfInfo" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" IsDiscriminator="true" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Information_Right" Member="Rights" ThisKey="InfoID" OtherKey="InfoID" Type="Right" />
      <Association Name="Information_InfoAboutGroup" Member="InfoAboutGroups" ThisKey="InfoID" OtherKey="InfoID" Type="InfoAboutGroup" />
      <Association Name="Information_Information" Member="Informations" ThisKey="InfoID" OtherKey="ParentInfoID" Type="Information" />
      <Association Name="Information_Information" Member="Information1" ThisKey="ParentInfoID" OtherKey="InfoID" Type="Information" IsForeignKey="true" />
      <Association Name="Message_Information" Member="Message" ThisKey="InfoInMessage" OtherKey="MessageID" Type="Message" IsForeignKey="true" />
      <Association Name="User_Information" Member="User" ThisKey="InfoAboutUser" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Type Name="StructuredInformation" InheritanceCode="Structured" IsInheritanceDefault="true" />
      <Type Name="SimpleInformation" InheritanceCode="Simple" />
    </Type>
  </Table>
</Database>